spring:
  application:
    name: user-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  data:
    mongodb:
      uri: ${MONGO_CONFIG:mongodb://localhost:27017/user-service}
#      host: localhost
#      port: 27017
#      database: user-service
      auto-index-creation : true
eureka:
  instance: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
server:
  port: 8081


