spring:
  application:
    name: project-service
  cloud:
        loadbalancer:
          ribbon:
            enabled: true
  kafka:
    consumer:
      auto-offset-reset: earliest

  data:
    mongodb:
      uri: ${MONGO_CONFIG:mongodb://localhost:27017/project-service}
      auto-index-creation: true
eureka:
    instance: localhost
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
server:
  port: 8082