spring:
  application:
    name: ticket-service
  cloud:
      loadbalancer:
        ribbon:
          enabled: true


  data:
    mongodb:
      host: localhost
      port: 27017
      database: ticket-service
      auto-index-creation: true
eureka:
  instance: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083