spring:
  application:
    name: ticket-service
  cloud:
      loadbalancer:
        ribbon:
          enabled: true


  data:
    mongodb:
      uri: ${MONGO_CONFIG:mongodb://localhost:27017/ticket-service}
      auto-index-creation: true
eureka:
  instance: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}
server:
  port: 8083